# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f572849fef19417f21008c513fc71b50c82719adbaef3684ceb27b540b48e45de0349444da8b1aa8ddfb1a13358a38aa5f7bbd9de398e3e13141b5e3eced25f0

test:
  secret_key_base: 69896f499db83b28ea5b69422be15d70401507c247f907a0be096b02e55d351d7de8f45040a28349c1e925a1685323429eae7d38181c58458732fa65908d438e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
